CREATE TABLE rooms(
  id                              INTEGER  NOT NULL PRIMARY KEY,
  name                            VARCHAR(255) NOT NULL,
  slug                            VARCHAR(255) NOT NULL,
  type                            VARCHAR(255) NOT NULL,
  price                           INTEGER  NOT NULL,
  size                            INTEGER  NOT NULL,
  capacity                        INTEGER  NOT NULL,
  pets                            VARCHAR(255) NOT NULL,
  breakfast                       VARCHAR(255) NOT NULL,
  featured                        VARCHAR(255) NOT NULL,
  description                     LONGTEXT NOT NULL,
  extras0                         VARCHAR(255) NOT NULL,
  extras1                         VARCHAR(255) NOT NULL,
  extras2                         VARCHAR(255) NOT NULL,
  extras3                         VARCHAR(255) NOT NULL,
  extras4                         VARCHAR(255) NOT NULL,
  extras5                         VARCHAR(255) NOT NULL,
  extras6                         VARCHAR(255) NOT NULL,
  fileurl1                        VARCHAR(255) NOT NULL,
  fileurl2                        VARCHAR(255) NOT NULL,
  fileurl3                        VARCHAR(255) NOT NULL,
  fileurl4                        VARCHAR(255) NOT NULL
);
INSERT INTO rooms(id,name,slug,type,price,size,capacity,pets,breakfast,featured,description,extras0,extras1,extras2,extras3,extras4,extras5,extras6,fileurl1,fileurl2,fileurl3,fileurl4) VALUES (1,'single economy','single-economy','single',100,200,1,'false','false','false','Street art edison bulb gluten-free, tofu try-hard lumbersexual brooklyn tattooed pickled chambray. Actually humblebrag next level, deep v art party wolf tofu direct trade readymade sustainable hell of banjo. Organic authentic subway tile cliche palo santo, street art XOXO dreamcatcher retro sriracha portland air plant kitsch stumptown. Austin small batch squid gastropub. Pabst pug tumblr gochujang offal retro cloud bread bushwick semiotics before they sold out sartorial literally mlkshk. Vaporware hashtag vice, sartorial before they sold out pok pok health goth trust fund cray.','Plush pillows and breathable bed linens','Soft, oversized bath towels','Fillsized, pH-balanced toiletries','Complimentary refreshments','Adequate safety/security','Internet','Comfortable beds','img1','room2','room3','room4');
INSERT INTO rooms(id,name,slug,type,price,size,capacity,pets,breakfast,featured,description,extras0,extras1,extras2,extras3,extras4,extras5,extras6,fileurl1,fileurl2,fileurl3,fileurl4) VALUES (2,'single basic','single-basic','single',150,250,1,'false','false','false','Street art edison bulb gluten-free, tofu try-hard lumbersexual brooklyn tattooed pickled chambray. Actually humblebrag next level, deep v art party wolf tofu direct trade readymade sustainable hell of banjo. Organic authentic subway tile cliche palo santo, street art XOXO dreamcatcher retro sriracha portland air plant kitsch stumptown. Austin small batch squid gastropub. Pabst pug tumblr gochujang offal retro cloud bread bushwick semiotics before they sold out sartorial literally mlkshk. Vaporware hashtag vice, sartorial before they sold out pok pok health goth trust fund cray.','Plush pillows and breathable bed linens','Soft, oversized bath towels','Fillsized, pH-balanced toiletries','Complimentary refreshments','Adequate safety/security','Internet','Comfortable beds','img2','room2','room3','room4');
INSERT INTO rooms(id,name,slug,type,price,size,capacity,pets,breakfast,featured,description,extras0,extras1,extras2,extras3,extras4,extras5,extras6,fileurl1,fileurl2,fileurl3,fileurl4) VALUES (3,'single standard','single-standard','single',250,300,1,'true','false','false','Street art edison bulb gluten-free, tofu try-hard lumbersexual brooklyn tattooed pickled chambray. Actually humblebrag next level, deep v art party wolf tofu direct trade readymade sustainable hell of banjo. Organic authentic subway tile cliche palo santo, street art XOXO dreamcatcher retro sriracha portland air plant kitsch stumptown. Austin small batch squid gastropub. Pabst pug tumblr gochujang offal retro cloud bread bushwick semiotics before they sold out sartorial literally mlkshk. Vaporware hashtag vice, sartorial before they sold out pok pok health goth trust fund cray.','Plush pillows and breathable bed linens','Soft, oversized bath towels','Fillsized, pH-balanced toiletries','Complimentary refreshments','Adequate safety/security','Internet','Comfortable beds','img3','room2','room3','room4');
INSERT INTO rooms(id,name,slug,type,price,size,capacity,pets,breakfast,featured,description,extras0,extras1,extras2,extras3,extras4,extras5,extras6,fileurl1,fileurl2,fileurl3,fileurl4) VALUES (4,'single deluxe','single-deluxe','single',300,400,1,'true','true','false','Street art edison bulb gluten-free, tofu try-hard lumbersexual brooklyn tattooed pickled chambray. Actually humblebrag next level, deep v art party wolf tofu direct trade readymade sustainable hell of banjo. Organic authentic subway tile cliche palo santo, street art XOXO dreamcatcher retro sriracha portland air plant kitsch stumptown. Austin small batch squid gastropub. Pabst pug tumblr gochujang offal retro cloud bread bushwick semiotics before they sold out sartorial literally mlkshk. Vaporware hashtag vice, sartorial before they sold out pok pok health goth trust fund cray.','Plush pillows and breathable bed linens','Soft, oversized bath towels','Fillsized, pH-balanced toiletries','Complimentary refreshments','Adequate safety/security','Internet','Comfortable beds','img4','room2','room3','room4');
INSERT INTO rooms(id,name,slug,type,price,size,capacity,pets,breakfast,featured,description,extras0,extras1,extras2,extras3,extras4,extras5,extras6,fileurl1,fileurl2,fileurl3,fileurl4) VALUES (5,'double economy','double-economy','double',200,300,2,'false','false','false','Street art edison bulb gluten-free, tofu try-hard lumbersexual brooklyn tattooed pickled chambray. Actually humblebrag next level, deep v art party wolf tofu direct trade readymade sustainable hell of banjo. Organic authentic subway tile cliche palo santo, street art XOXO dreamcatcher retro sriracha portland air plant kitsch stumptown. Austin small batch squid gastropub. Pabst pug tumblr gochujang offal retro cloud bread bushwick semiotics before they sold out sartorial literally mlkshk. Vaporware hashtag vice, sartorial before they sold out pok pok health goth trust fund cray.','Plush pillows and breathable bed linens','Soft, oversized bath towels','Fillsized, pH-balanced toiletries','Complimentary refreshments','Adequate safety/security','Internet','Comfortable beds','img5','room2','room3','room4');
INSERT INTO rooms(id,name,slug,type,price,size,capacity,pets,breakfast,featured,description,extras0,extras1,extras2,extras3,extras4,extras5,extras6,fileurl1,fileurl2,fileurl3,fileurl4) VALUES (6,'double basic','double-basic','double',250,350,2,'false','false','false','Street art edison bulb gluten-free, tofu try-hard lumbersexual brooklyn tattooed pickled chambray. Actually humblebrag next level, deep v art party wolf tofu direct trade readymade sustainable hell of banjo. Organic authentic subway tile cliche palo santo, street art XOXO dreamcatcher retro sriracha portland air plant kitsch stumptown. Austin small batch squid gastropub. Pabst pug tumblr gochujang offal retro cloud bread bushwick semiotics before they sold out sartorial literally mlkshk. Vaporware hashtag vice, sartorial before they sold out pok pok health goth trust fund cray.','Plush pillows and breathable bed linens','Soft, oversized bath towels','Fillsized, pH-balanced toiletries','Complimentary refreshments','Adequate safety/security','Internet','Comfortable beds','img6','room2','room3','room4');
INSERT INTO rooms(id,name,slug,type,price,size,capacity,pets,breakfast,featured,description,extras0,extras1,extras2,extras3,extras4,extras5,extras6,fileurl1,fileurl2,fileurl3,fileurl4) VALUES (7,'double standard','double-standard','double',300,400,2,'true','false','false','Street art edison bulb gluten-free, tofu try-hard lumbersexual brooklyn tattooed pickled chambray. Actually humblebrag next level, deep v art party wolf tofu direct trade readymade sustainable hell of banjo. Organic authentic subway tile cliche palo santo, street art XOXO dreamcatcher retro sriracha portland air plant kitsch stumptown. Austin small batch squid gastropub. Pabst pug tumblr gochujang offal retro cloud bread bushwick semiotics before they sold out sartorial literally mlkshk. Vaporware hashtag vice, sartorial before they sold out pok pok health goth trust fund cray.','Plush pillows and breathable bed linens','Soft, oversized bath towels','Fillsized, pH-balanced toiletries','Complimentary refreshments','Adequate safety/security','Internet','Comfortable beds','img7','room2','room3','room4');
INSERT INTO rooms(id,name,slug,type,price,size,capacity,pets,breakfast,featured,description,extras0,extras1,extras2,extras3,extras4,extras5,extras6,fileurl1,fileurl2,fileurl3,fileurl4) VALUES (8,'double deluxe','double-deluxe','double',400,500,2,'true','true','true','Street art edison bulb gluten-free, tofu try-hard lumbersexual brooklyn tattooed pickled chambray. Actually humblebrag next level, deep v art party wolf tofu direct trade readymade sustainable hell of banjo. Organic authentic subway tile cliche palo santo, street art XOXO dreamcatcher retro sriracha portland air plant kitsch stumptown. Austin small batch squid gastropub. Pabst pug tumblr gochujang offal retro cloud bread bushwick semiotics before they sold out sartorial literally mlkshk. Vaporware hashtag vice, sartorial before they sold out pok pok health goth trust fund cray.','Plush pillows and breathable bed linens','Soft, oversized bath towels','Fillsized, pH-balanced toiletries','Complimentary refreshments','Adequate safety/security','Internet','Comfortable beds','/static/media/room-8.ebb7fca5.jpeg','room2','room3','room4');
INSERT INTO rooms(id,name,slug,type,price,size,capacity,pets,breakfast,featured,description,extras0,extras1,extras2,extras3,extras4,extras5,extras6,fileurl1,fileurl2,fileurl3,fileurl4) VALUES (9,'family economy','family-economy','family',300,500,3,'false','false','false','Street art edison bulb gluten-free, tofu try-hard lumbersexual brooklyn tattooed pickled chambray. Actually humblebrag next level, deep v art party wolf tofu direct trade readymade sustainable hell of banjo. Organic authentic subway tile cliche palo santo, street art XOXO dreamcatcher retro sriracha portland air plant kitsch stumptown. Austin small batch squid gastropub. Pabst pug tumblr gochujang offal retro cloud bread bushwick semiotics before they sold out sartorial literally mlkshk. Vaporware hashtag vice, sartorial before they sold out pok pok health goth trust fund cray.','Plush pillows and breathable bed linens','Soft, oversized bath towels','Fillsized, pH-balanced toiletries','Complimentary refreshments','Adequate safety/security','Internet','Comfortable beds','img9','room2','room3','room4');
INSERT INTO rooms(id,name,slug,type,price,size,capacity,pets,breakfast,featured,description,extras0,extras1,extras2,extras3,extras4,extras5,extras6,fileurl1,fileurl2,fileurl3,fileurl4) VALUES (10,'family basic','family-basic','family',350,550,4,'false','false','false','Street art edison bulb gluten-free, tofu try-hard lumbersexual brooklyn tattooed pickled chambray. Actually humblebrag next level, deep v art party wolf tofu direct trade readymade sustainable hell of banjo. Organic authentic subway tile cliche palo santo, street art XOXO dreamcatcher retro sriracha portland air plant kitsch stumptown. Austin small batch squid gastropub. Pabst pug tumblr gochujang offal retro cloud bread bushwick semiotics before they sold out sartorial literally mlkshk. Vaporware hashtag vice, sartorial before they sold out pok pok health goth trust fund cray.','Plush pillows and breathable bed linens','Soft, oversized bath towels','Fillsized, pH-balanced toiletries','Complimentary refreshments','Adequate safety/security','Internet','Comfortable beds','img10','room2','room3','room4');
INSERT INTO rooms(id,name,slug,type,price,size,capacity,pets,breakfast,featured,description,extras0,extras1,extras2,extras3,extras4,extras5,extras6,fileurl1,fileurl2,fileurl3,fileurl4) VALUES (11,'family standard','family-standard','family',400,600,5,'true','false','false','Street art edison bulb gluten-free, tofu try-hard lumbersexual brooklyn tattooed pickled chambray. Actually humblebrag next level, deep v art party wolf tofu direct trade readymade sustainable hell of banjo. Organic authentic subway tile cliche palo santo, street art XOXO dreamcatcher retro sriracha portland air plant kitsch stumptown. Austin small batch squid gastropub. Pabst pug tumblr gochujang offal retro cloud bread bushwick semiotics before they sold out sartorial literally mlkshk. Vaporware hashtag vice, sartorial before they sold out pok pok health goth trust fund cray.','Plush pillows and breathable bed linens','Soft, oversized bath towels','Fillsized, pH-balanced toiletries','Complimentary refreshments','Adequate safety/security','Internet','Comfortable beds','img11','room2','room3','room4');
INSERT INTO rooms(id,name,slug,type,price,size,capacity,pets,breakfast,featured,description,extras0,extras1,extras2,extras3,extras4,extras5,extras6,fileurl1,fileurl2,fileurl3,fileurl4) VALUES (12,'family deluxe','family-deluxe','family',500,700,6,'true','true','true','Street art edison bulb gluten-free, tofu try-hard lumbersexual brooklyn tattooed pickled chambray. Actually humblebrag next level, deep v art party wolf tofu direct trade readymade sustainable hell of banjo. Organic authentic subway tile cliche palo santo, street art XOXO dreamcatcher retro sriracha portland air plant kitsch stumptown. Austin small batch squid gastropub. Pabst pug tumblr gochujang offal retro cloud bread bushwick semiotics before they sold out sartorial literally mlkshk. Vaporware hashtag vice, sartorial before they sold out pok pok health goth trust fund cray.','Plush pillows and breathable bed linens','Soft, oversized bath towels','Fillsized, pH-balanced toiletries','Complimentary refreshments','Adequate safety/security','Internet','Comfortable beds','/static/media/details-4.7569a316.jpeg','room2','room3','room4');
INSERT INTO rooms(id,name,slug,type,price,size,capacity,pets,breakfast,featured,description,extras0,extras1,extras2,extras3,extras4,extras5,extras6,fileurl1,fileurl2,fileurl3,fileurl4) VALUES (13,'presidential','presidential-room','presidential',600,1000,10,'true','true','true','Street art edison bulb gluten-free, tofu try-hard lumbersexual brooklyn tattooed pickled chambray. Actually humblebrag next level, deep v art party wolf tofu direct trade readymade sustainable hell of banjo. Organic authentic subway tile cliche palo santo, street art XOXO dreamcatcher retro sriracha portland air plant kitsch stumptown. Austin small batch squid gastropub. Pabst pug tumblr gochujang offal retro cloud bread bushwick semiotics before they sold out sartorial literally mlkshk. Vaporware hashtag vice, sartorial before they sold out pok pok health goth trust fund cray.','Plush pillows and breathable bed linens','Soft, oversized bath towels','Fillsized, pH-balanced toiletries','Complimentary refreshments','Adequate safety/security','Internet','Comfortable beds','/static/media/details-2.50c23e62.jpeg','room2','room3','room4');
